# Generated by Django 4.1 on 2025-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='fecha_subida',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(default='Contenido sin título', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenido',
            name='archivo',
            field=models.FileField(upload_to='contenido/'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
