# Generated by Django 4.1 on 2025-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fecha_subida_contenido_creado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='creador',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('creador', 'Creador de contenido'), ('suscriptor', 'Suscriptor')], default='suscriptor', max_length=20),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10),
        ),
    ]
