# Generated by Django 4.1 on 2025-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_compra_estado_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('creador', 'Creador de contenido'), ('suscriptor', 'Suscriptor'), ('administrador', 'administrador')], default='suscriptor', max_length=20),
        ),
    ]
