# Generated by Django 4.1 on 2025-06-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('creador', 'Creador de contenido'), ('suscriptor', 'Suscriptor'), ('administrador', 'Administrador')], default='suscriptor', max_length=20),
        ),
    ]
