# Generated by Django 4.1 on 2025-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rut',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_correo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_fecha_nacimiento',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_rut',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
